### ISSUE TITLE
Crash on start when prometheus is enabled

### ISSUE THREAD

**Issue by Reecepbcups** [CosmWasm/wasmd#1592] opened 2023-08-31 23:31 UTC
## Versions
Go: 1.20.4
Wasmd version: v0.41.0
WasmVM: v1.3.0
SDK: v0.47.4
Juno: [v17.0.0-alpha.1](https://github.com/CosmosContracts/juno/releases/tag/v17.0.0-alpha.1)
`libwasmvm.x86_64.so => /home/juno-testnet/go/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.3.0/internal/api/libwasmvm.x86_64.so (0x00007ff9ab0f1000)`

## Issue
On the start of the new upgraded binary (from vm1.2.4->1.3.0), it panics and exits the process if you have `prometheus = true` in your chain's `config/config.toml` file.
*This also happened on a Chihuahua chain upgrade in the past.*

## Temporary Solution
Toggling `prometheus = false` and restarting the node resolves the issue. 

## Error log
```
Sep 01 01:33:59 testnet-desktop cosmovisor_uni-6[1029648]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 01 01:33:59 testnet-desktop cosmovisor_uni-6[1029648]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1f53760]
Sep 01 01:33:59 testnet-desktop cosmovisor_uni-6[1029648]: goroutine 1056 [running]:
Sep 01 01:33:59 testnet-desktop cosmovisor_uni-6[1029648]: github.com/CosmWasm/wasmd/x/wasm/keeper.(*WasmVMMetricsCollector).Collect(0xc0016a26c0, 0xc005b29f60?)
Sep 01 01:33:59 testnet-desktop cosmovisor_uni-6[1029648]:         github.com/CosmWasm/wasmd@v0.41.0/x/wasm/keeper/metrics.go:56 +0x40
Sep 01 01:33:59 testnet-desktop cosmovisor_uni-6[1029648]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
Sep 01 01:33:59 testnet-desktop cosmovisor_uni-6[1029648]:         github.com/prometheus/client_golang@v1.16.0/prometheus/registry.go:455 +0x10d
Sep 01 01:33:59 testnet-desktop cosmovisor_uni-6[1029648]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
Sep 01 01:33:59 testnet-desktop cosmovisor_uni-6[1029648]:         github.com/prometheus/client_golang@v1.16.0/prometheus/registry.go:466 +0x59d
Sep 01 01:33:59 testnet-desktop cosmovisor_uni-6[1029627]: Error: exit status 2
Sep 01 01:33:59 testnet-desktop cosmovisor_uni-6[1029627]: 1:33AM ERR error="exit status 2" module=cosmovisor
```

**Comment by alpe** [comment] 2023-09-01 06:57
Thanks @Reecepbcups  for reporting! This is an ugly 🐛 that slipped in. We have the fix in main already (thanks to @dadamu ) and will release this soon with v0.42.0.

I am closing this as duplicate of https://github.com/CosmWasm/wasmd/issues/1574

**Closed by alpe** 2023-09-01 06:57 UTC
