### ISSUE TITLE
How to enable swagger on wasmd?

### ISSUE THREAD

**Issue by dev573** [CosmWasm/wasmd#1314] opened 2023-04-03 16:49 UTC
We have configure the `app.toml` file of our chain and also set enable and swagger to true. Configured the `openapi.yaml` file under the `docs/static`, but when we hit on port `1317`. getting the `error` message.
```
{
"code": 12,
"message": "Not Implemented",
"details": []
}
```

**Comment by dev573** [comment] 2023-04-03 17:46
Also i found out these two code snippet related to this 
```
	if apiConfig.Swagger {
		RegisterSwaggerAPI(apiSvr.Router)
	}
```
and 
```
func RegisterSwaggerAPI(rtr *mux.Router) {
	statikFS, err := fs.New()
	if err != nil {
		panic(err)
	}

	staticServer := http.FileServer(statikFS)
	rtr.PathPrefix("/swagger/").Handler(http.StripPrefix("/swagger/", staticServer))
}
```
So, if my swagger file `openapi.yaml` file under the `docs/static`, how should i configure this ?

**Comment by pinosu** [comment] 2023-04-10 12:18
Hello, as discussed on discord, the issue is most likely with privacy policy settings on your browser.
Please try to modify the settings in your broswer.
I will close this issue because wasmd works fine as demonstrated by curling the /swagger endpoint.

![Screenshot_2023-04-09_at_9 38 05_AM](https://user-images.githubusercontent.com/95283998/230899885-f3dd37d0-6efb-4f84-b580-9f49a8ac8276.png)

**Closed by pinosu** 2023-04-10 12:18 UTC
