### ISSUE TITLE
bug: submessages broken when using `WithMessageHandler`

### ISSUE THREAD

**Issue by Reecepbcups** [CosmWasm/wasmd#1735] opened 2023-11-20 23:25 UTC
## Bug
Submessages do not work via contract since v0.43.

Juno's Uni testnet has had this with 
- 0.43 + wasmvm 1.4
- 0.45 + wasmvm 1.5  (upgraded to today). 

This did not happen on 0.42.

Codebase: [Juno v18.0.0-alpha.3](https://github.com/CosmosContracts/juno/tree/v18.0.0-alpha.3)

[Terp network has also had this issue (reported in the cosmwasm discord)](https://discord.com/channels/737637324434833438/737643344712171600/1173740796030234674)

### Full Error 0.43
```
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: dispatch: submessages: unknown message from the contract [CosmWasm/wasmd@v0.43.0/x/wasm/keeper/keeper.go:1247] With gas wanted: '100000000' and gas used: '115661' : unknown request
9:36AM ERR failure when running app err="rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: dispatch: submessages: unknown message from the contract [CosmWasm/wasmd@v0.43.0/x/wasm/keeper/keeper.go:1247] With gas wanted: '100000000' and gas used: '115661' : unknown request"
```

### Full error 0.45
```
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: dispatch: submessages: unknown message from the contract [CosmWasm/wasmd@v0.45.0/x/wasm/keeper/keeper.go:1247] With gas wanted: '100000000' and gas used: '117137' : unknown request
12:06AM ERR failure when running app err="rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: dispatch: submessages: unknown message from the contract [CosmWasm/wasmd@v0.45.0/x/wasm/keeper/keeper.go:1247] With gas wanted: '100000000' and gas used: '117137' : unknown request"
```

## Reproduce:
(credit to mr_t of Ark protocol for this)
```
- Compile https://github.com/CosmWasm/cw-nfts/tree/main/contracts/cw721-base  (code id 3743 on Uni testnet)

# create contract instance
junod tx wasm instantiate 3743 '{"name":"Reece #00001", "symbol":"juno-reece-test-#00001", "minter":"juno15twk6xu5rnrrlnf7c5zy92gvykcs4h5ucxzzqq"}' --from validator --label 'JUNO Ark Test #00001' --admin juno15twk6xu5rnrrlnf7c5zy92gvykcs4h5ucxzzqq --gas-prices 0.0045ujunox --gas auto --gas-adjustment 1.5 -b sync --yes --node https://uni-rpc.reece.sh:443 --chain-id uni-6 --output json

# mint token
junod tx wasm execute juno1jvx62zqj3wucmwuxa9e8uuawv9ljgzg22uhjzw7mze2x9tamcz8qhrq7xt '{"mint": {"token_id":"00000", "owner":"juno15twk6xu5rnrrlnf7c5zy92gvykcs4h5ucxzzqq" }}' --from validator --gas-prices 0.0045ujunox --gas auto --gas-adjustment 1.5 -b sync --chain-id uni-6 --node https://uni-rpc.reece.sh:443 --yes --output json

# use a sub message from any contract
junod tx wasm execute juno1jvx62zqj3wucmwuxa9e8uuawv9ljgzg22uhjzw7mze2x9tamcz8qhrq7xt '{"send_nft": { "contract": "juno16u3qcynv998c6yt9kpr32anm55prsusmvp0exlk6u45lp5rk3rhqjzmdfp", "token_id": "00000", "msg": "b2s=" }}' --from validator --gas-prices 0.0045ujunox --gas auto --gas-adjustment 1.3 -b sync --yes --output json --chain-id uni-6 --node https://uni-rpc.reece.sh:443
```

Reported to affect their testnet contracts by:
- James O
- Mr T
- Whalelphant

## Request
add a e2e with submessage execution along with the patch

**Comment by alpe** [comment] 2023-11-21 13:56
Thank you @Reecepbcups for your bug report!

Sub-message handling is a core part of wasmd and any problems are very had to trace on test or production systems. 
I have tried to replicate the issue that you reported with the last release artifact of `cw721-base` and also the code with id 3743 that you had referenced in your report with our vanilla wasmd but failed. 
@chipshort was so kind to contribute a test contract for the receiver side so that we had a full contract-to-contract setup in e2e and system tests.

When I took a brief look at the linked Juno version, I could see that not the default wasmd message handler was used but a custom setup is [passed](https://github.com/CosmosContracts/juno/blob/v18.0.0-alpha.3/app/keepers/keepers.go#L526) to the wasm keeper. Our `BurnCoinMessageHandler` handles only one specific message and fails for all the others. This setup seems to be the root cause for your problems.
The keeper options come with a lot of power and almost no docs. In your case it may have been easier to chain your burn handler setup before the default handler chain  You can find an [example](https://github.com/osmosis-labs/mesh-security-sdk/blob/v0.3.0-rc.0/demo/app/app.go#L585-L589) in the MS repo.

I would close this issue tomorrow.

**Comment by Reecepbcups** [comment] 2023-11-21 16:55
Thank you so much for this! I really appreciate it :smile: 

I had not considered it being related to the BurnPlugin since that is only Juno specific. Looks like Terp network blindly copy pasted that into their repo which is why it affected them too.

**Comment by hard-nett** [comment] 2023-11-22 00:57
Thank you for the the insight & examples from both of you, much more clarity on the wasmOpts 👍

**Closed** 2023-11-22 01:31 UTC
